name: sphinx-build

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: kdbogusz
  GITHUB_REPOSITORY: kdbogusz/gi-yagit


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install -y git rsync python3-pip graphviz doxygen
        shell: bash
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -f .gitignore
          cd docs/
          pip3 install -r requirements.txt
          make clean
          mkdir build
          cd source/
          doxygen
          cd ../
          make html
                    
          touch .nojekyll
          
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          git status
          git add .
          
          git commit -am "Updating Docs for commit ${GITHUB_SHA}"
        shell: bash
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
