name: sphinx-build

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: kdbogusz
  GITHUB_REPOSITORY: kdbogusz/gi-yagit


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install -y git rsync python3-pip graphviz doxygen
        shell: bash
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Build and Commit
        uses: sphinx-notes/pages@2.0
        with:
          documentation_path: docs/source
          requirements_path: docs/source/requirements.txt
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
